export const reData = [
    {
        id:1,
        country:"한국",
        brand:"시그니엘",
        hotel:"시그니엘 서울",
    },
    {
        id:2,
        country:"한국",
        brand:"시그니엘",
        hotel:"시그니엘 부산",
    },
     {
        id:3,
        country:"한국",
        brand:"롯데호텔",
        hotel:"시그니엘 서울",
    },
     {
        id:4,
        country:"한국",
        brand:"롯데호텔",
        hotel:"롯데호텔 월드",
    },
     {
        id:5,
        country:"한국",
        brand:"롯데호텔",
        hotel:"롯데호텔 부산",
    },
     {
        id:6,
        country:"한국",
        brand:"롯데호텔",
        hotel:"롯데호텔 제주",
    },
     {
        id:7,
        country:"한국",
        brand:"롯데호텔",
        hotel:"롯데호텔 울산",
    },
     {
        id:8,
        country:"한국",
        brand:"L7 바이 롯데호텔",
        hotel:"L7 강남 바이 롯데호텔",
    },
     {
        id:9,
        country:"한국",
        brand:"L7 바이 롯데호텔",
        hotel:"L7 홍대 바이 롯데호텔",
    },
     {
        id:10,
        country:"한국",
        brand:"L7 바이 롯데호텔",
        hotel:"L7 명동 바이 롯데호텔",
    },
     {
        id:11,
        country:"한국",
        brand:"L7 바이 롯데호텔",
        hotel:"L7 해운대 바이 롯데호텔",
    },
     {
        id:12,
        country:"한국",
        brand:"L7 바이 롯데호텔",
        hotel:"L7 충장 바이 롯데호텔",
    },
     {
        id:13,
        country:"한국",
        brand:"브리브 바이 롯데호텔",
        hotel:"브리브 광주 바이 롯데호텔",
    },
     {
        id:14,
        country:"한국",
        brand:"롯데시티호텔",
        hotel:"롯데시티호텔 김포공항",
    },
     {
        id:15,
        country:"한국",
        brand:"롯데시티호텔",
        hotel:"롯데시티호텔 구로",
    },
     {
        id:16,
        country:"한국",
        brand:"롯데시티호텔",
        hotel:"롯데시티호텔 마포",
    },
     {
        id:17,
        country:"한국",
        brand:"롯데시티호텔",
        hotel:"롯데시티호텔 명동",
    },
     {
        id:18,
        country:"한국",
        brand:"롯데시티호텔",
        hotel:"롯데시티호텔 제주",
    },
     {
        id:19,
        country:"한국",
        brand:"롯데시티호텔",
        hotel:"롯데시티호텔 대전",
    },
     {
        id:20,
        country:"한국",
        brand:"롯데시티호텔",
        hotel:"롯데시티호텔 울산",
    },
     {
        id:21,
        country:"한국",
        brand:"롯데리조트",
        hotel:"아트빌라스 제주",
    },
     {
        id:22,
        country:"한국",
        brand:"롯데리조트",
        hotel:"롯데리조트 부여",
    },
     {
        id:23,
        country:"한국",
        brand:"롯데리조트",
        hotel:"롯데호텔앤리조트 김해",
    },
     {
        id:24,
        country:"한국",
        brand:"롯데리조트",
        hotel:"롯데리조트 속초",
    },
     {
        id:25,
        country:"일본",
        brand:"롯데호텔",
        hotel:"롯데아라이리조트",
    },
     {
        id:26,
        country:"일본",
        brand:"롯데시티호텔",
        hotel:"롯데시티호텔 긴시초",
    },
     {
        id:27,
        country:"미얀마",
        brand:"롯데호텔",
        hotel:"롯데호텔 양곤",
    },
     {
        id:28,
        country:"우즈베키스탄",
        brand:"롯데시티호텔",
        hotel:"롯데시티호텔 타슈켄트팰리스",
    },
    {
        id:29,
        country:"베트남",
        brand:"롯데호텔",
        hotel:"롯데호텔 하노이",
    },
    {
        id:30,
        country:"베트남",
        brand:"롯데호텔",
        hotel:"롯데호텔 사이공",
    },
    {
        id:31,
        country:"베트남",
        brand:"L7 바이 롯데호텔",
        hotel:"L7 웨스트 레이크 하노이 바이 롯데호텔",
    },
    {
        id:32,
        country:"미국",
        brand:"롯데호텔",
        hotel:"롯데뉴욕팰리스",
    },
    {
        id:33,
        country:"미국",
        brand:"롯데호텔",
        hotel:"롯데호텔 괌",
    },
     {
        id:34,
        country:"미국",
        brand:"롯데호텔",
        hotel:"롯데호텔 시애틀",
    },
    {
        id:35,
        country:"베트남",
        brand:"L7 바이 롯데호텔",
        hotel:"L7 시카고 바이 롯데호텔",
    },
    {
        id:36,
        country:"미국",
        brand:"AFFILIATED by LOTTE HOTELS",
        hotel:"뉴욕커 호텔 바이 롯데호텔",
    },
     {
        id:37,
        country:"러시아",
        brand:"롯데호텔",
        hotel:"롯데호텔 모스크바",
    },
     {
        id:38,
        country:"러시아",
        brand:"롯데호텔",
        hotel:"롯데호텔 상트페테르부르크",
    },
     {
        id:39,
        country:"러시아",
        brand:"롯데호텔",
        hotel:"롯데호텔 사마라",
    },
     {
        id:40,
        country:"러시아",
        brand:"롯데호텔",
        hotel:"롯데호텔 블라디보스토크",
    },
]